# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'git@github.com:sumup/cocoapods-specs.git'
source 'https://cdn.cocoapods.org'

target 'Banner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Banner
  pod 'CircuitUI/Swift',             '~> 0.2.0'
end
